#!/bin/bash -e

source ./cyberteach.conf

cat << EOF > ./.env
TZ=${TIME_ZONE}
HTTP_USERNAME=${HTTP_USER}
HTTP_PASSWORD=${HTTP_PASSWD}
HOSTNAME=${HOSTNAME}
DOMAINNAME=${DOMAINNAME}
CF_API_EMAIL=${CF_API_EMAIL}
CF_API_KEY=${CF_API_KEY}
# ENV variables which are required for cyberteach front end Classsroom
LOADBALANCER_SECRET=${LOADBALANCER_SECRET}
SECRET_KEY_BASE=${SECRET_KEY_BASE}
LOADBALANCER_HOSTNAME=${LOADBALANCER_HOSTNAME}
BIGBLUEBUTTON_ENDPOINT=${BIGBLUEBUTTON_ENDPOINT}
BIGBLUEBUTTON_SECRET=${BIGBLUEBUTTON_SECRET}
ALLOW_GREENLIGHT_ACCOUNTS=${ALLOW_GREENLIGHT_ACCOUNTS}
ALLOW_MAIL_NOTIFICATIONS=${ALLOW_MAIL_NOTIFICATIONS}
GREENLIGHT_DOMAIN=${GREENLIGHT_DOMAIN}
SMTP_FROM=${SMTP_FROM}
SMTP_SERVER=${SMTP_SERVER}
SMTP_PORT=${SMTP_PORT}
SMTP_DOMAIN=${SMTP_DOMAIN}
SMTP_USERNAME=${SMTP_USERNAME}
SMTP_PASSWORD=${SMTP_PASSWORD}
SMTP_AUTH=${SMTP_AUTH}
SMTP_STARTTLS_AUTO=${SMTP_STARTTLS_AUTO}
SMTP_SENDER=${SMTP_SENDER}
RELATIVE_URL_ROOT=${RELATIVE_URL_ROOT}
ROOM_FEATURES=${ROOM_FEATURES}
PAGINATION_NUMBER=${PAGINATION_NUMBER}
NUMBER_OF_ROWS=${NUMBER_OF_ROWS}
MAINTENANCE_MODE=${MAINTENANCE_MODE}
REPORT_ISSUE_URL=
DB_ADAPTER=${DB_ADAPTER}
DB_HOST=${DB_HOST}
DB_NAME=${DB_NAME}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
DEFAULT_REGISTRATION=${DEFAULT_REGISTRATION}
EOF
