version: '2'

networks:
  bbb-backend-net:

services:
  bbb:
    image: hub.cybergate.lk/cyberteach/bbb:1.0.0
    privileged: true
    environment:
      - "NAME=${NAME}"
      - "DOMAIN=${DOMAIN}"
    hostname: ${NAME}.${DOMAIN}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - container=docker
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - ./certs/:/local/certs/
      - /var/run/docker.sock:/var/run/docker.sock
      - ../src/:/home/bbb/src/
    security_opt:
      - seccomp:unconfined
    networks:
      - bbb-backend-net

  
