version: '3'

services:
  traefik:
    hostname: traefik
    image: traefik:v1.7.16
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - t1_proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:${HOSTNAME}.${DOMAINNAME}; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=t1_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${HOSTNAME}.${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${HOSTNAME}.${DOMAINNAME}"
#      - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - ./shared:/shared

  db:
    image: postgres:9.5
    container_name: db
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - greenlight_db:/var/lib/postgresql/data
    networks:
      - default
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks: 
      - default  
      
  classroom:
    entrypoint: [bin/start]
    image: hub.cybergate.lk/cyberteach/classroom:2.2.0
    container_name: classroom
    restart: always
    volumes:
      - greenlight_logs:/usr/src/app/log
    env_file: ./.env   
    networks:
      - t1_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=classroom"
      - "traefik.frontend.rule=Host:${HOSTNAME}.${DOMAINNAME}; PathPrefix: /classroom"
      - "traefik.port=80"
      - "traefik.docker.network=t1_proxy" 
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${HOSTNAME}.${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${HOSTNAME}.${DOMAINNAME}"
    links:
      - db
  bbb:
    image: hub.cybergate.lk/cyberteach/bbb:2.3.0
    restart: unless-stopped
    privileged: true
    environment:
      - "NAME=${HOSTNAME}"
      - "DOMAIN=${DOMAINNAME}"
    hostname: ${HOSTNAME}.${DOMAINNAME}
    container_name: bbb
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - IPC_LOCK
      - NET_RAW
      - NET_BROADCAST
      - SYS_NICE
      - SYS_RESOURCE
    environment:b
      - container=docker
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/src/:/home/bbb/src/
    security_opt:
      - seccomp:unconfined
    env_file: 
      - ./.env
    networks: 
      - default
      - t1_proxy
    labels:  
      - "traefik.enable=true"
      - "traefik.docker.network=t1_proxy"
      - "traefik.one.backend=bbb"
      - "traefik.one.port=8090"
      - "traefik.one.frontend.rule=Host:${HOSTNAME}.${DOMAINNAME}; PathPrefix: /bigbluebutton"
      - "traefik.one.frontend.headers.SSLRedirect=true"
      - "traefik.one.frontend.headers.STSSeconds=315360000"
      - "traefik.one.frontend.headers.browserXSSFilter=true"
      - "traefik.one.frontend.headers.contentTypeNosniff=true"
      - "traefik.one.frontend.headers.forceSTSHeader=true"
      - "traefik.one.frontend.headers.SSLHost=${HOSTNAME}.${DOMAINNAME}"
      - "traefik.one.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.one.frontend.headers.STSPreload=true"
      - "traefik.one.frontend.headers.frameDeny=true"
      - "traefik.two.backend=bbb"
      - "traefik.two.port=3008"
      - "traefik.two.frontend.rule=Host:${HOSTNAME}.${DOMAINNAME}; PathPrefix: /bbb-webrtc-sfu"
      - "traefik.two.frontend.headers.SSLRedirect=true"
      - "traefik.two.frontend.headers.STSSeconds=315360000"
      - "traefik.two.frontend.headers.browserXSSFilter=true"
      - "traefik.two.frontend.headers.contentTypeNosniff=true"
      - "traefik.two.frontend.headers.forceSTSHeader=true"
      - "traefik.two.frontend.headers.SSLHost=${HOSTNAME}.${DOMAINNAME}"
      - "traefik.two.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.two.frontend.headers.STSPreload=true"
      - "traefik.two.frontend.headers.frameDeny=true"
      - "traefik.three.backend=bbb"
      - "traefik.three.port=3000"
      - "traefik.three.frontend.rule=Host:${HOSTNAME}.${DOMAINNAME}; PathPrefix: /html5client,/_timesync"
      - "traefik.three.frontend.headers.SSLRedirect=true"
      - "traefik.three.frontend.headers.STSSeconds=315360000"
      - "traefik.three.frontend.headers.browserXSSFilter=true"
      - "traefik.three.frontend.headers.contentTypeNosniff=true"
      - "traefik.three.frontend.headers.forceSTSHeader=true"
      - "traefik.three.frontend.headers.SSLHost=${HOSTNAME}.${DOMAINNAME}"
      - "traefik.three.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.three.frontend.headers.STSPreload=true"
      - "traefik.three.frontend.headers.frameDeny=true"  
      - "traefik.four.backend=bbb"
      - "traefik.four.port=7443"
      - "traefik.four.wss.protocol=https"
      - "traefik.four.frontend.rule=Host:${HOSTNAME}.${DOMAINNAME}; PathPrefix: /ws"
      - "traefik.four.frontend.headers.SSLRedirect=true"
      - "traefik.four.frontend.headers.STSSeconds=315360000"
      - "traefik.four.frontend.headers.browserXSSFilter=true"
      - "traefik.four.frontend.headers.contentTypeNosniff=true"
      - "traefik.four.frontend.headers.forceSTSHeader=true"
      - "traefik.four.frontend.headers.SSLHost=${HOSTNAME}.${DOMAINNAME}"
      - "traefik.four.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.four.frontend.headers.STSPreload=true"
      - "traefik.four.frontend.headers.frameDeny=true"
      
  adminer:
    image: adminer:4.6.3-standalone
    container_name: adminer
    restart: always
    networks:
      - t1_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=adminer"
      - "traefik.frontend.rule=Host:${HOSTNAME}.${DOMAINNAME}; PathPrefix: /dbadmin"
      - "traefik.port=8080"
      - "traefik.docker.network=t1_proxy" 
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${HOSTNAME}.${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${HOSTNAME}.${DOMAINNAME}"
    depends_on:
      - db 
      
networks:
  t1_proxy:
    external:
      name: t1_proxy
  default:
    driver: bridge
    
volumes:
  traefik-acme:
  greenlight_db:
  greenlight_logs:

 

  
