version: '2'

networks:
  bbb-backend-net:

services:
  
  letsencrypt:
    image: linuxserver/letsencrypt
    restart: unless-stopped
    container_name: letsencrypt
    hostname: letsencrypt
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    volumes:
      - ./volumes/letsencrypt/config:/config
    env_file: 
      - ./.letsencrypt.env
    networks:
      - bbb-backend-net 

  bbb:
    image: hub.cybergate.lk/cyberteach/bbb:1.0.0
    restart: unless-stopped
    privileged: true
    environment:
      - "NAME=${NAME}"
      - "DOMAIN=${DOMAIN}"
    hostname: ${NAME}.${DOMAIN}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - container=docker
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - ./volumes/letsencrypt/configetc/letsencrypt:/local/certs/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/src/:/home/bbb/src/
    security_opt:
      - seccomp:unconfined
    env_file: 
      - ./.bbb.env
    networks:
      - bbb-backend-net

  
